In [2]:
import numpy as np
np.__version__

'1.18.1'

In [4]:
myarray = np.arange(1,5)
display(myarray)

array([1, 2, 3, 4])

In [6]:
my_list=[2,3,4,6,10]
mya2 = np.array(my_list)
display(mya2)
type(mya2)


array([ 2,  3,  4,  6, 10])

numpy.ndarray

In [8]:
mya2*(10 + 2j)

array([ 20. +4.j,  30. +6.j,  40. +8.j,  60.+12.j, 100.+20.j])